# Generated by Django 4.2.26 on 2026-03-23 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ftsAnimais/')),
                ('descricao', models.TextField(blank=True)),
                ('meta', models.FloatField(default=0.0)),
                ('arrecadado', models.FloatField(blank=True, default=0.0, null=True)),
                ('adotado', models.BooleanField(default=False)),
                ('adotadoPor', models.CharField(blank=True, max_length=100, null=True)),
                ('historia', models.CharField(blank=True, max_length=1000, null=True)),
                ('diaAdocao', models.DateField(blank=True, null=True)),
                ('porte', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
